kind: Deployment
apiVersion: apps/v1
metadata:
  name: autograder-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autograder
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        app: autograder
    spec:
      volumes:
      - name: app
        emptyDir: {}
        
      initContainers:
      - name: get-assignments
        image: docker.io/bitnami/git:latest
        securityContext:
          allowPrivilegeEscalation: true
        env:
        - name: HOME
          value: /home/init
        - name: autograder_DEPLOY_KEY
          valueFrom:
            secretKeyRef:
              name: autograder-deploy-key
              key: ssh-privatekey
        envFrom:
        - secretRef:
            name: autograder-config   
              

        command:
        - sh
        - -c
        - |
          cd $HOME
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          echo "${autograder_DEPLOY_KEY}\n" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519" git clone ${autograder_REPO_SSH_URL}
          rm -rf ~/.ssh/id_ed25519
          find . -type d -name 'solutions' -exec rm -rf {} +

        volumeMounts:
        - name: app
          mountPath: /home/init

      containers:
      - name: autograder-is
        image: autograder-is:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        envFrom:
        - secretRef:
            name: autograder-config
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
            
        volumeMounts:
        - name: app
          mountPath: /app/assignments
